### ISSUE TITLE
No Files

### ISSUE THREAD

**Issue by yupoff** [BigPoro/LargeTitle#1]
There are no files in the project:
NormalNavView.h
NormalNavView.m
DynamicBigTitleView.h
DynamicBigTitleView.m
DynamicNavView.h
DynamicNavView.m
UIViewController+DynamicBar.h
UIViewController+DynamicBar.m
UIView+GoAdd.h
UIView+GoAdd.m

**Comment by BigPoro** [comment]
已添加
